import { test, expect } from '@playwright/test';

test('Owner setup, project creation, authorization, sign out and sign in', async ({ page, context }) => {
  const pageErrors: string[] = []; page.on('pageerror', (e) => pageErrors.push(e.message));
  await page.goto('/setup');
  await page.getByLabel('Company name', { exact: true }).fill('Browser Test Company');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByLabel('Your name', { exact: true }).fill('Test Owner');
  await page.getByLabel('Username', { exact: true }).fill('test-owner');
  await page.getByLabel('Password (min. 10 characters)', { exact: true }).fill('test-owner-password-123');
  await page.getByLabel('Confirm password', { exact: true }).fill('test-owner-password-123');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Re-check', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByRole('button', { name: 'Launch company', exact: true }).click();
  await expect(page.getByText('Company launched.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Open the company', exact: true }).click();
  await expect(page).toHaveURL('/');
  await page.goto('/projects');
  await page.getByRole('button', { name: 'New project', exact: true }).click();
  await page.getByLabel('Name', { exact: true }).fill('Browser Regression Project');
  await page.getByLabel('Objective', { exact: true }).fill('Verify project creation without using live AI credentials');
  await page.getByRole('button', { name: 'Create project', exact: true }).click();
  await expect(page).toHaveURL(/\/projects\/[a-f0-9-]+$/);
  await expect(page.getByRole('heading', { name: 'Browser Regression Project', exact: true })).toBeVisible();
  const pid = new URL(page.url()).pathname.split('/').pop();
  const detail = await (await page.request.get(`/api/projects/${pid}`)).json();
  expect(detail.engineeringLock.locked).toBe(true);
  expect((await page.request.post('/api/projects', { data: { name: 'CSRF', objective: 'Must be rejected' } })).status()).toBe(403);
  expect((await page.request.post('/api/auth/logout', { headers: { 'x-aco-csrf': '1' }, data: {} })).ok()).toBe(true);
  await context.clearCookies();
  expect((await page.request.get('/api/dashboard')).status()).toBe(401);
  await page.goto('/login');
  await page.getByLabel('Username', { exact: true }).fill('test-owner');
  await page.getByLabel('Password', { exact: true }).fill('wrong-password');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByText('Invalid username or password', { exact: true })).toBeVisible();
  await page.getByLabel('Password', { exact: true }).fill('test-owner-password-123');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL('/');
  expect(pageErrors).toEqual([]);
});
